name = "LegacyConnectors"
uuid = "a57253b0-1ecd-4843-b9c3-e020d5da5ff8"
version = "0.1.0"
authors = ["NumericalEarth organization (github.com/NumericalEarth) and lovely contributors"]

[deps]
Breeze = "660aa2fb-d4c8-4359-a52c-9c057bc511da"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Breeze = "0.4"
DelimitedFiles = "1"
julia = "1.11"
