struct Sounding{F}
    surface_pressure       :: Float64
    potential_temperature  :: F
    specific_humidity      :: F
    x_momentum             :: F
    y_momentum             :: F
    format                 :: Symbol
    source                 :: String
end

Base.length(s::Sounding) = size(s.potential_temperature, 3)

function Base.show(io::IO, s::Sounding)
    θ_sfc  = s.potential_temperature[1, 1, 1]
    qᵛ_sfc = s.specific_humidity[1, 1, 1]
    print(io, "Sounding(", s.format, ", ", length(s), " z-cells, ",
          "p_sfc=", round(s.surface_pressure / 100; digits = 2), " mb, ",
          "θ_sfc=", round(θ_sfc; digits = 2), " K, ",
          "qᵛ_sfc=", round(qᵛ_sfc * 1000; digits = 2), " g/kg)")
end

"""
    Sounding(path::AbstractString; format::Symbol = :input_sounding) -> Sounding
    Sounding(name::Symbol)                                            -> Sounding

Construct a vertical sounding from a file path, or from the name of one
of the bundled examples (see [`example_sounding`](@ref) for the list).

The returned `Sounding{F}` is concretely typed: its four profile fields
— `potential_temperature`, `specific_humidity`, `x_momentum`,
`y_momentum` — are all Oceananigans `Field{Nothing, Nothing, Face}`s on
a column grid whose z-faces are exactly the file's z-levels (with
`0.0` prepended for the surface). They index, broadcast, and plot like
any other Oceananigans field, and they are filled onto a Breeze model
grid with `Oceananigans.Fields.interpolate!`.

`specific_humidity` may contain `NaN` at levels where the source did
not provide moisture (e.g. mesospheric levels of a GFS point profile).

`format` selects the on-disk format. Currently supported:

  - `:input_sounding` — the CM1/WRF/ERF text format (default).

```julia
s = Sounding("/path/to/input_sounding")
s = Sounding(:weisman_klemp_1982)
```
"""
function Sounding(path::AbstractString; format::Symbol = :input_sounding)
    if format === :input_sounding
        return _read_input_sounding(path)
    else
        throw(ArgumentError(
            "Unknown sounding format $(repr(format)). Supported: :input_sounding."))
    end
end

Sounding(name::Symbol) = Sounding(example_sounding(name))

"""
    example_sounding(name::Symbol) -> String

Return the absolute path to a bundled example sounding. Dispatches on
`Val(name)`, so adding a new bundled example is a one-line method
definition:

```julia
LegacyConnectors.example_sounding(::Val{:my_new_one}) =
    joinpath(pkgdir(LegacyConnectors), "data", "soundings", "my_new_one.txt")
```

Built-in names:

  - `:weisman_klemp_1982` — analytic supercell sounding from
    Weisman & Klemp (1982); generated by
    `data/soundings/generate_weisman_klemp_1982.jl`.
  - `:kabq_radiosonde`    — observed KABQ (Albuquerque) radiosonde,
    2025-07-15 00Z.
  - `:abudhabi_gfs`       — GFS point forecast at Abu Dhabi,
    2025-07-15 12Z; mesospheric qᵛ levels are `NaN`.
"""
example_sounding(name::Symbol) = example_sounding(Val(name))

example_sounding(::Val{:weisman_klemp_1982}) =
    _bundled_sounding_path("weisman_klemp_1982.txt")

example_sounding(::Val{:kabq_radiosonde}) =
    _bundled_sounding_path("input_sounding_kabq_radiosonde_2025-07-15_00z.txt")

example_sounding(::Val{:abudhabi_gfs}) =
    _bundled_sounding_path("input_sounding_abudhabi_gfs_2025-07-15_12z.txt")

# Fallback for symbols nobody has registered. Introspects which
# `Val{:thing}` specializations of `example_sounding` exist so the
# error message stays in sync with whatever's been defined.
function example_sounding(::Val{name}) where {name}
    available = sort(_registered_example_sounding_names())
    throw(ArgumentError(
        "Unknown example sounding $(repr(name)). Available: " *
        join(repr.(available), ", ") * "."))
end

_bundled_sounding_path(file) =
    joinpath(pkgdir(LegacyConnectors), "data", "soundings", file)

function _registered_example_sounding_names()
    names = Symbol[]
    for m in methods(example_sounding)
        sig = m.sig
        sig isa DataType || continue
        params = sig.parameters
        length(params) == 2 || continue
        T = params[2]
        T isa DataType && T <: Val || continue
        tp = T.parameters
        length(tp) == 1 && tp[1] isa Symbol && push!(names, tp[1])
    end
    return names
end
