"""
    Sounding

A vertical profile of an idealized atmosphere parsed from a legacy-model
sounding file. All quantities are in SI units after parsing:

  - `surface_pressure :: Float64` — Pa
  - `surface_θ        :: Float64` — K (potential temperature)
  - `surface_qv       :: Float64` — kg/kg (water vapor mixing ratio)
  - `z, θ, qv, u, v`  :: `Vector{Float64}` — height (m AGL), θ (K),
    qv (kg/kg), u (m/s), v (m/s); levels above the surface, sorted by
    ascending `z`.
  - `format :: Symbol` — e.g. `:input_sounding`.
  - `source :: String` — original file path, used in error messages.

`qv` may contain `NaN` at levels where the source file did not provide
a moisture value (e.g. mesospheric levels of a GFS point profile).
"""
struct Sounding
    surface_pressure :: Float64
    surface_θ        :: Float64
    surface_qv       :: Float64
    z  :: Vector{Float64}
    θ  :: Vector{Float64}
    qv :: Vector{Float64}
    u  :: Vector{Float64}
    v  :: Vector{Float64}
    format :: Symbol
    source :: String

    function Sounding(p_sfc, θ_sfc, qv_sfc, z, θ, qv, u, v, format, source)
        n = length(z)
        length(θ)  == n || throw(ArgumentError("θ has length $(length(θ)) but expected $n"))
        length(qv) == n || throw(ArgumentError("qv has length $(length(qv)) but expected $n"))
        length(u)  == n || throw(ArgumentError("u has length $(length(u)) but expected $n"))
        length(v)  == n || throw(ArgumentError("v has length $(length(v)) but expected $n"))
        n > 0 || throw(ArgumentError("sounding has no above-surface levels"))
        issorted(z) || throw(ArgumentError("sounding heights are not monotonically increasing"))
        return new(p_sfc, θ_sfc, qv_sfc, z, θ, qv, u, v, format, source)
    end
end

Base.length(s::Sounding) = length(s.z)

function Base.show(io::IO, s::Sounding)
    print(io, "Sounding(", s.format, ", ", length(s), " levels, ",
          "p_sfc=", round(s.surface_pressure / 100; digits=2), " mb, ",
          "θ_sfc=", round(s.surface_θ; digits=2), " K, ",
          "qv_sfc=", round(s.surface_qv * 1000; digits=2), " g/kg)")
end

"""
    read_sounding(path; format=:input_sounding) -> Sounding

Read a sounding file. Currently supported `format`s:

  - `:input_sounding` — the CM1/WRF/ERF text format (default).

Unknown formats raise an `ArgumentError` listing the supported set.
"""
function read_sounding(path::AbstractString; format::Symbol=:input_sounding)
    if format === :input_sounding
        return _read_input_sounding(path)
    else
        throw(ArgumentError(
            "Unknown sounding format $(repr(format)). Supported: :input_sounding."))
    end
end

"""
    example_sounding(name::Symbol) -> String

Return the absolute path to one of the bundled example soundings:

  - `:weisman_klemp_1982` — analytic supercell sounding from
    Weisman & Klemp (1982); generated by `data/soundings/generate_weisman_klemp_1982.jl`.
  - `:kabq_radiosonde`    — observed KABQ (Albuquerque) radiosonde,
    2025-07-15 00Z; elevated surface, 95 levels.
  - `:abudhabi_gfs`       — GFS point forecast at Abu Dhabi,
    2025-07-15 12Z; 32 levels with `NaN` moisture aloft.
"""
function example_sounding(name::Symbol)
    file = if name === :weisman_klemp_1982
        "weisman_klemp_1982.txt"
    elseif name === :kabq_radiosonde
        "input_sounding_kabq_radiosonde_2025-07-15_00z.txt"
    elseif name === :abudhabi_gfs
        "input_sounding_abudhabi_gfs_2025-07-15_12z.txt"
    else
        throw(ArgumentError(
            "Unknown example sounding $(repr(name)). Available: " *
            ":weisman_klemp_1982, :kabq_radiosonde, :abudhabi_gfs."))
    end
    return joinpath(pkgdir(LegacyConnectors), "data", "soundings", file)
end
