"""
    Sounding{F}

A vertical sounding parsed from a legacy-model file. The four profile
fields are Oceananigans `Field`s of type `Field{Nothing, Nothing, Center}`
on a column grid — they index, broadcast, and plot the same way as any
other Oceananigans field, and they're filled onto a Breeze model grid
with `Oceananigans.Fields.interpolate!` (the package extends
`interpolate!` to handle the column-to-3D case).

`Sounding` is concretely typed: `F` is the specific column-`Field` type
produced by the parser, so all four profile fields share a single
concrete type and the struct can be specialized by Julia at use sites.

# Fields

- `surface_pressure        :: Float64`  — surface pressure (Pa)
- `potential_temperature   :: F`        — θ (K)
- `specific_humidity       :: F`        — qᵛ (kg/kg)
- `x_momentum              :: F`        — u (m/s)
- `y_momentum              :: F`        — v (m/s)
- `format                  :: Symbol`   — e.g. `:input_sounding`
- `source                  :: String`   — original file path

Each profile field has `N + 1` z-cells: the first at `z = 0` (the
surface) and the next `N` at the above-surface levels from the file.
`specific_humidity` may contain `NaN` at levels where the source did
not provide moisture.

# Construction

    Sounding(path::AbstractString; format = :input_sounding)
    Sounding(name::Symbol)

The latter looks the file up via [`example_sounding`](@ref):

```julia
s = Sounding("/path/to/input_sounding")
s = Sounding(:weisman_klemp_1982)
```
"""
struct Sounding{F}
    surface_pressure       :: Float64
    potential_temperature  :: F
    specific_humidity      :: F
    x_momentum             :: F
    y_momentum             :: F
    format                 :: Symbol
    source                 :: String
end

Base.length(s::Sounding) = size(s.potential_temperature, 3)

function Base.show(io::IO, s::Sounding)
    θ_sfc  = s.potential_temperature[1, 1, 1]
    qᵛ_sfc = s.specific_humidity[1, 1, 1]
    print(io, "Sounding(", s.format, ", ", length(s), " z-cells, ",
          "p_sfc=", round(s.surface_pressure / 100; digits = 2), " mb, ",
          "θ_sfc=", round(θ_sfc; digits = 2), " K, ",
          "qᵛ_sfc=", round(qᵛ_sfc * 1000; digits = 2), " g/kg)")
end

function Sounding(path::AbstractString; format::Symbol = :input_sounding)
    if format === :input_sounding
        return _read_input_sounding(path)
    else
        throw(ArgumentError(
            "Unknown sounding format $(repr(format)). Supported: :input_sounding."))
    end
end

Sounding(name::Symbol) = Sounding(example_sounding(name))

"""
    example_sounding(name::Symbol) -> String

Return the absolute path to one of the bundled example soundings:

  - `:weisman_klemp_1982` — analytic supercell sounding from
    Weisman & Klemp (1982); generated by
    `data/soundings/generate_weisman_klemp_1982.jl`.
  - `:kabq_radiosonde`    — observed KABQ (Albuquerque) radiosonde,
    2025-07-15 00Z.
  - `:abudhabi_gfs`       — GFS point forecast at Abu Dhabi,
    2025-07-15 12Z; mesospheric qᵛ levels are `NaN`.
"""
function example_sounding(name::Symbol)
    file = if name === :weisman_klemp_1982
        "weisman_klemp_1982.txt"
    elseif name === :kabq_radiosonde
        "input_sounding_kabq_radiosonde_2025-07-15_00z.txt"
    elseif name === :abudhabi_gfs
        "input_sounding_abudhabi_gfs_2025-07-15_12z.txt"
    else
        throw(ArgumentError(
            "Unknown example sounding $(repr(name)). Available: " *
            ":weisman_klemp_1982, :kabq_radiosonde, :abudhabi_gfs."))
    end
    return joinpath(pkgdir(LegacyConnectors), "data", "soundings", file)
end
